// @sms/db — Prisma client singleton + re-exported types.
// NOTE: `@prisma/client` is generated by `pnpm db:generate`; until then editors
// will flag the import. The RLS layer is enforced in Postgres, not here.

export * from "@prisma/client";
import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient; readPrisma?: PrismaClient };

const logLevels: ("warn" | "error")[] =
  process.env.NODE_ENV === "development" ? ["warn", "error"] : ["error"];

/**
 * App-wide (PRIMARY / writer) Prisma client. The application connects as the
 * least-privilege role (`major_user`); migrations run separately under the
 * privileged role. Tenant isolation (RLS) is applied per-request via
 * `SET LOCAL app.current_school_id` — see the API's tenant runner, not this
 * client directly. In production `DATABASE_URL` should point at the connection
 * pooler (RDS Proxy / PgBouncer, transaction mode) — the tenant GUC is set with
 * `set_config(..., true)` (transaction-local), which is pooler-safe.
 */
export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({ log: logLevels });

/**
 * The replica to read from, or null when there is none to use.
 *
 * A replica URL IDENTICAL to the primary's is not a replica. The Terraform used
 * to hand every single-database deployment exactly that (so the key always
 * existed), and a separate client was opened for it: a SECOND connection pool
 * per task against the same primary, and the replica router, seeing two
 * clients, ran its bookkeeping — a lag probe every second, an extra query per
 * write — for a replica that was not there. Empty is unset too (an env var set
 * to "" is not a value).
 */
export function replicaUrlOf(env: Record<string, string | undefined>): string | null {
  const replica = env.DATABASE_REPLICA_URL?.trim();
  if (!replica) return null;
  if (replica === env.DATABASE_URL?.trim()) return null;
  return replica;
}

/**
 * READ-REPLICA client for scaling read load off the primary writer. When
 * `DATABASE_REPLICA_URL` is set (e.g. an Aurora reader endpoint), the API's
 * read-only tenant path (`runAsTenantReadOnly`) routes aggregate/list queries
 * here; when it is UNSET this IS the primary client, so single-database
 * deployments behave identically with zero code changes. RLS + the per-request
 * GUC apply on the replica exactly as on the primary.
 */
export const readPrisma: PrismaClient =
  globalForPrisma.readPrisma ??
  ((replica) => (replica ? new PrismaClient({ datasourceUrl: replica, log: logLevels }) : prisma))(
    replicaUrlOf(process.env),
  );

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
  globalForPrisma.readPrisma = readPrisma;
}
