// @sms/db — Prisma client singleton + re-exported types.
// NOTE: `@prisma/client` is generated by `pnpm db:generate`; until then editors
// will flag the import. The RLS layer is enforced in Postgres, not here.

export * from "@prisma/client";
import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };

/**
 * App-wide Prisma client. The application connects as the least-privilege role
 * (`major_user`); migrations run separately under the privileged role. Tenant
 * isolation (RLS) is applied per-request via `SET LOCAL app.current_school_id`
 * — see the API's tenant runner, not this client directly.
 */
export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: process.env.NODE_ENV === "development" ? ["warn", "error"] : ["error"],
  });

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
